### ISSUE TITLE
run at a ati radeon 7700 wrong:Extension "GL_EXT_shader _texture_lod" is not supported

### ISSUE THREAD

**Issue by gaibohan** [ruofeidu/DuEngine#11]
when I run the demo in a GTX 750 TI ,all it's fine.
when I run then demo in a ati radeon 7700 ,it say:
Fragment shader failed to compile with the following errors:
ERROR: 0:2: error(#61) Required extension is not found. Extension "GL_EXT_shader
_texture_lod" is not supported

GTX 750TI OpenGL Version：450
ATI OpenGL Version：460

sorry,my english is not good.

**Comment by ruofeidu** [comment]
Thank you for creating the first issue! English is never a problem, any question is welcome!

Please go to "DuEngine/shadertoy.uniforms.glsl" and comment out the second line:

#extension GL_EXT_shader_texture_lod : require

Most shader demo without using texture2DLod should be working fine now.

AMD Radeon™ HD 7700 is a five-year-old card, so perhaps it does not support shader level-of-details.

Good luck!

**Comment by ruofeidu** [comment]
Please let me know it this solves your problem.

**Comment by gaibohan** [comment]
Thank you very much for your reply! 
When I commented the code,now the program is running well.
I have bought a new video card.
I still have a doubt,GTX 750TI OpenGL Version is 450,ATI OpenGL Version is 460,but it not support "GL_EXT_shader_texture_lod",How do I avoid program crashes in programming？
Sorry,my english is not good.
